### ISSUE TITLE
Left Neck Cylinder Missing Lower Plate Mounting Screw

### ISSUE THREAD

**Issue by Fuelrush** [input-inc/OpenSaint#1]
Left Neck Cylinder Missing Lower Plate Mounting Screw. Right cylinder screw selected and shown.

![Neck Cylinder Mounting Plate Screw Missing](https://user-images.githubusercontent.com/102781464/184039709-d7ea86cb-b45c-4ae2-9bce-f473c361ea8b.jpg)

**Comment by Hackmancoltaire** [comment]
The left and right are just configurations of the same assembly. I'm seeing 3 screws in the `Bottom Ball Mounting Plate Screws` folder. that are visible in both configurations. Check that the parts are in the folder and aren't hidden. 
![image](https://user-images.githubusercontent.com/341149/206882682-dfc89ab3-f08d-498f-af9d-ff14d9968e69.png)

**Comment by Hackmancoltaire** [comment]
Parts were actually there, just needed to be unsuppressed.
